title: Trivial
description: Trivial libraries contain a lot of utilities, models, extensions and components as one of .NET supplementary, which are useful but trivial, to help you to focus the business logic of your projects.
theme: jekyll-theme-midnight
